Gatekeeper addon e2e tests
vmware-tanzu/community-edition pull request #1068
Opened 2021-07-14 11:06 UTC by JitenPalaparthi

## What this PR does / why we need it

Contains  e2e tests for Gatekeeper addon along with few helper methods. All below mentioned steps are automated.
 - Step-1 ```tanzu package install gatekeeper.tce.vmware.com ``` 
 - Step-2  ```kubectl apply -f  ${TCE-REPO-DIR}addons/packages/gatekeeper/test/e2e/fixtures/constraint-template.yaml/constraint-template.yaml```
  - Step-3 Check required CRDs after applying the Step-2 file. ```  kubectl get crds | grep -i k8srequiredlabels ```
  - Step-4   ``` kubectl apply -f ${TCE-REPO-DIR}addons/packages/gatekeeper/test/e2e/fixtures/constraint.yaml```
  - Step-5  ``` kubectl create ns test ```  User cannot create a namespace without owner (The actual use case)
  - Step-6  `` kubectl apply -f ${TCE-REPO-DIR}addons/packages/gatekeeper/test/e2e/fixtures/test-namespace.yaml``` 
               - After applying the Step-6 file , name space should be created as the namespace will be created with owner name.
          
## Which issue(s) this PR fixes

Fixes: # [1061](https://github.com/vmware-tanzu/tce/issues/1061)

## Describe testing done for PR

Tests done on Standalone cluster using ginkgo and go test
## Special notes for your reviewer

N/A
## Does this PR introduce a user-facing change?

N/A
```release-note

```

2021-07-14 21:57 UTC, jpmcb requested changes
Awesome! Thanks for adding these

We are about to split up the top level go module into individual go modules in https://github.com/vmware-tanzu/tce/pull/735. This way, package and plugin authors can have greater ownership over their own modules and there won't be any top level dependencies. See this issue for dicsussions and details: https://github.com/vmware-tanzu/tce/pull/753

Can you update this PR with it's own go mod? And then we will be able to merge it after https://github.com/vmware-tanzu/tce/pull/735

2021-07-20 16:14 UTC, jpmcb requested changes
Awesome! Thanks for adding those

The markdown linter is failing. Can you run `make check` to ensure there is proper formatting of the readme file?

2021-07-21 15:35 UTC, jpmcb requested changes

2021-10-12 20:16 UTC, joshrosso commented
:wave: -- hello, we've decided to close stale PRs, but do acknowledge that this is something we may want to get in eventually. We noticed it currently exists in your fork. If you'd like to re-open a PR with updated E2E tests, we'd love to take a look at them!

2021-10-12 20:16 UTC, closed without merging