Bump Contour to 1.17.1
vmware-tanzu/community-edition pull request #1160
Opened 2021-07-23 15:10 UTC by sunjayBhatia

## What this PR does / why we need it
Bumps Contour to 1.17.1 for https://github.com/projectcontour/contour/security/advisories/GHSA-5ph6-qq5x-7jwc

## Which issue(s) this PR fixes
N/A

## Describe testing done for PR
TBD

## Special notes for your reviewer
N/A

## Does this PR introduce a user-facing change?

```release-note
Kubernetes Services of type ExternalName will now not be processed by Contour.
```

Also see Contour release note: https://github.com/projectcontour/contour/releases/tag/v1.17.1

2021-07-23 15:32 UTC, skriss requested changes
Also need to add the new version to https://github.com/vmware-tanzu/tce/blob/main/addons/repos/main.yaml#L7-L9

2021-07-23 15:52 UTC, skriss reviewed
:+1: LGTM, just have the one question on the Package bundle SHA which we need some input from TCE maintainers on.

2021-07-26 19:00 UTC, skriss approved these changes
LGTM

2021-07-26 20:02 UTC, seemiller approved these changes
LGTM

2021-07-26 20:02 UTC, merged