Doc uninstall
vmware-tanzu/community-edition pull request #1285
Opened 2021-08-12 11:14 UTC by kcoriordan

- [ ] - [ ] closes: #1076

uninstall Tanzu CLI

- [ ] Updates form @dvonthenen based on old PR review: #1267 (DONE)

 -PR #1271 changed folder to `'tce'`
 -removed step to delete installation folder using `rm`
 -add uninstall.sh script for mac
 
- [ ] add topic for deleting workload clusters (DONE)

2021-08-12 16:30 UTC, joshrosso requested changes
@kcoriordan thanks for getting this knocked out!

Can you squash and re-write your commit message to be more descriptive? We're trying to get better as we go to GA that the commit messages actually provide context on what was done.

2021-08-16 20:19 UTC, davidvonthenen reviewed
3 updates and we are good!

2021-08-18 15:18 UTC, davidvonthenen approved these changes

2021-08-18 16:39 UTC, jpmcb approved these changes
LGTM!!

2021-08-19 10:34 UTC, merged