Adds content for conformance command
vmware-tanzu/community-edition pull request #1407
Opened 2021-08-23 11:49 UTC by kcoriordan

Signed-off-by: kcoriordan <koriordan@vmware.com>

## What this PR does / why we need it
Adds doc  content for conformance command

## Details for the Release Notes
This is already covered in v0.7.0 release note

## Which issue(s) this PR fixes

Fixes: #1405 

## Describe testing done for PR
Previewed here: https://deploy-preview-1407--quirky-franklin-8969be.netlify.app/docs/latest/getting-started-standalone/#run-tanzu-conformance-command

## Special notes for your reviewer
This is minimum content to get something in, but it definitely could do with some rounding out, or use case

2021-08-26 15:58 UTC, davidvonthenen submitted a review, later dismissed
This seems reasonable.... but I actually havent used the command and we probably need @nrb to see if this is technically accurate

2021-09-01 18:39 UTC, nrb requested changes
I think this is good! I don't think we need to repeat all of the Sonobuoy docs, because it should be a 1:1 mapping for Sonobuoy commands with the root command swapped from `sonobuoy` to `tanzu conformance`.

I had a few comments, but only one I really consider blocking.

2021-09-09 15:45 UTC, nrb submitted a review, later dismissed

2021-09-09 16:11 UTC, joshrosso approved these changes

2021-09-09 16:11 UTC, merged