add darwin arm64 build target, improve m1 devx
vmware-tanzu/community-edition pull request #1480
Opened 2021-08-28 22:07 UTC by joefitzgerald

Signed-off-by: Joe Fitzgerald <jfitzgerald@vmware.com>

## What this PR does / why we need it

This PR causes darwin / arm64 binaries to be generated by `make release`. It also makes improvements to scripts that support building a release locally on an arm64 Mac.

## Details for the Release Notes

```release-note
generate arm64 binaries for darwin
```

## Which issue(s) this PR fixes

N/A

## Describe testing done for PR

* ran `make release` locally and validated it succeeds

## Special notes for your reviewer

* This PR will be accompanied with a `cayman_vmware-tanzu_tce` MR to ensure the new binaries are notarized correctly.

2021-08-30 18:19 UTC, navidshaikh submitted a review, later dismissed

2021-08-31 14:12 UTC, davidvonthenen reviewed
I left a comment... and I'm going to private message you about the signing process.

2021-08-31 14:13 UTC, davidvonthenen approved these changes
This looks good to me!

2021-09-01 23:54 UTC, davidvonthenen requested changes
Please see comment above. This PR is good but I have work on the build infra side to support this.

EDIT: Going to try to do this week.

2021-09-02 16:47 UTC, nrb reviewed
@joefitzgerald Are you able to build the `tanzu` binary with this?

I ask because the tanzu-framework Makefile [defines a small subset of environments](https://github.com/vmware-tanzu/tanzu-framework/blob/main/Makefile#L83), and it's [checked](https://github.com/vmware-tanzu/tanzu-framework/blob/main/Makefile#L248) such that it shouldn't compile.

I did a search for PRs on tanzu-framework but couldn't find any.

2021-09-02 18:55 UTC, davidvonthenen approved these changes
LGTM. thanks for this awesome contribution!

2021-09-02 19:04 UTC, merged