bump tanzu-framework to 0.2.0
vmware-tanzu/community-edition pull request #1592
Opened 2021-09-07 16:22 UTC by joshrosso

## What this PR does / why we need it

This commit bumps our tanzu-framework dependency to 0.2.0 for:

* building of all tanzu-framework owned plugins
* our standalone-cluster plugin

This does not impact the dependencies of our conformance and diagnostics
plugin.

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
tanzu-framework version bumped to 0.2.0
```

## Which issue(s) this PR fixes

* Fixes: https://github.com/vmware-tanzu/community-edition/issues/1273
* Fixes: https://github.com/vmware-tanzu/community-edition/issues/1381
* Relates: https://github.com/vmware-tanzu/community-edition/issues/655
    * Note this is **not** fixed

## Describe testing done for PR

* https://github.com/vmware-tanzu/community-edition/issues/1273

Verified CEIP is off for management cluster creation

```
$ CLUSTER_PLAN=dev tanzu management-cluster create -i docker henrow -v 9
compatibility file (/home/josh/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
BOM files inside /home/josh/.config/tanzu/tkg/bom already exists, skipping download
cluster config file not provided using default config file at '/home/josh/.config/tanzu/tkg/cluster-config.yaml'
CEIP Opt-in status: false

Validating the pre-requisites...
Identity Provider not configured. Some authentication features won't work
```

Verified CEIP is off for standalone clusters

```
$ tanzu standalone-cluster create -i docker henrow -v 9
compatibility file (/home/josh/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
BOM files inside /home/josh/.config/tanzu/tkg/bom already exists, skipping download
cluster config file not provided using default config file at '/home/josh/.config/tanzu/tkg/cluster-config.yaml'
CEIP Opt-in status: false
timeout duration of at least 15 minutes is required, using default timeout 30m0s
```

* https://github.com/vmware-tanzu/community-edition/issues/1381

Verified TMC integration is no longer an issue.

![image](https://user-images.githubusercontent.com/6200057/132708975-ffcef5bc-3dbc-4098-9741-82656f5d1652.png)

* 🚨 [still broken] https://github.com/vmware-tanzu/community-edition/issues/655

Verified UX remains inconsistent for cluster names of standalone clusters

![image](https://user-images.githubusercontent.com/6200057/132710438-d5b97570-ef29-4885-895a-0098142f4796.png)

![image](https://user-images.githubusercontent.com/6200057/132710497-b623aa4c-675d-4264-9b17-bdd4effaa106.png)

![image](https://user-images.githubusercontent.com/6200057/132710550-d4a4f8eb-1adc-4977-8644-84d3fe0be554.png)

```
$ tanzu standalone-cluster create -i docker
Error: no cluster name specified
Usage:
  tanzu standalone-cluster create <cluster name> -f <configuration location> [flags]

Flags:
```

## Special notes for your reviewer

Review the testing validation above.

2021-09-07 22:26 UTC, davidvonthenen requested changes
This file needs to be bumped also:
https://github.com/vmware-tanzu/community-edition/blob/main/hack/FRAMEWORK_BUILD_VERSION

2021-09-09 15:08 UTC, davidvonthenen submitted a review, later dismissed

2021-09-09 15:23 UTC, jpmcb requested changes
nit: Missing `go.sum` entries for this new bump. When I pull down this PR and run `make lint`, the `cli/cmd/plugin/standalone-cluster/go.sum` entry is dirty and needs to be updated:
```
❯ git diff go.sum

cli/cmd/plugin/standalone-cluster/go.sum

───────────────────────────────────────────────────────────────────────────────────────┐
1176: github.com/vmware-tanzu/carvel-vendir v0.19.0 h1:4FTeDcxwEuZWdFlFqh+11NqnJciCkkO │
───────────────────────────────────────────────────────────────────────────────────────┘
│1176│github.com/vmware-tanzu/carvel-vendir v0.19.0/go.mod h1:HF7iLB0NyEFHuCvM0EJ42fERk20→│1176│github.com/vmware-tanzu/carvel-vendir v0.19.0/go.mod h1:HF7iLB0NyEFHuCvM0EJ42fERk20→
│1177│github.com/vmware-tanzu/cluster-api v0.3.23-0.20210722162135-d31e78c28159 h1:c7sM3N→│1177│github.com/vmware-tanzu/cluster-api v0.3.23-0.20210722162135-d31e78c28159 h1:c7sM3N→
│1178│github.com/vmware-tanzu/cluster-api v0.3.23-0.20210722162135-d31e78c28159/go.mod h1→│1178│github.com/vmware-tanzu/cluster-api v0.3.23-0.20210722162135-d31e78c28159/go.mod h1→
│1179│github.com/vmware-tanzu/tanzu-framework v1.4.0-pre-alpha-2.0.20210903135334-7be2aa6→│1179│github.com/vmware-tanzu/tanzu-framework v1.4.0-pre-alpha-2.0.20210909135501-d143f23→
│1180│github.com/vmware-tanzu/tanzu-framework v1.4.0-pre-alpha-2.0.20210903135334-7be2aa6→│1180│github.com/vmware-tanzu/tanzu-framework v1.4.0-pre-alpha-2.0.20210909135501-d143f23→
│1181│github.com/vmware/govmomi v0.20.3/go.mod h1:URlwyTFZX72RmxtxuaFL2Uj3fD1JTvZdx59bHWk→│1181│github.com/vmware/govmomi v0.20.3/go.mod h1:URlwyTFZX72RmxtxuaFL2Uj3fD1JTvZdx59bHWk→
│1182│github.com/vmware/govmomi v0.23.1 h1:vU09hxnNR/I7e+4zCJvW+5vHu5dO64Aoe2Lw7Yi/KRg=   │1182│github.com/vmware/govmomi v0.23.1 h1:vU09hxnNR/I7e+4zCJvW+5vHu5dO64Aoe2Lw7Yi/KRg=
│1183│github.com/vmware/govmomi v0.23.1/go.mod h1:Y+Wq4lst78L85Ge/F8+ORXIWiKYqaro1vhAulAC→│1183│github.com/vmware/govmomi v0.23.1/go.mod h1:Y+Wq4lst78L85Ge/F8+ORXIWiKYqaro1vhAulAC→

```

2021-09-09 15:34 UTC, jpmcb approved these changes

2021-09-09 16:14 UTC, merged