Implements package `README.md` copy utility program also copying images
vmware-tanzu/community-edition pull request #1789
Opened 2021-09-16 19:43 UTC by jpmcb

## What this PR does / why we need it
This PR accomplishes 2 things 
- Finds any files found in a package's `images/` directory and copies them to the `docs/ site/content/docs/latest/images/` directory, keeping the image name intact 
- Modifies the copies package readme to allow for hugo to properly render any images that are referenced. Primarily, with how the docs are structured as of this writing, it replaces
```
[My image link](images/my-informative-image.jpeg
```
with the following
```
[My image link](../images/my-informative-image.jpeg)
```

We can see this now rendering correctly for the external dns package docs:
![Screen Shot 2021-09-16 at 1 28 43 PM](https://user-images.githubusercontent.com/23109390/133675423-e52914ac-ae86-4942-94b7-080aaff388c6.png)

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
Docs now correctly render images in package readmes
```

## Which issue(s) this PR fixes
Fixes: https://github.com/vmware-tanzu/community-edition/issues/1739

## Describe testing done for PR
Ran locally with `hugo serve` and verified the external-dns readme has it's imaged served (see screenshot above)

## Special notes for your reviewer
Note: this _does_ create a precidence that if package authors want to include images in their readmes and want them rendered correctly in the docs, they _must_ place those JPEGs or PNGs under an `images/` directory [much like external DNS is doing at the time of this writing](https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/external-dns/0.8.0/images)

Therefore, the convention would be to have images under
```
addons/packages/{PACKAGE-NAME}/{PACKAGE-VERSION}/images
```
and to be referenced in their readmes as
```
[Link to image](images/{IMAGE-NAME}.jpeg)
```

2021-09-16 20:02 UTC, seemiller submitted a review, later dismissed
LGTM

2021-09-17 21:50 UTC, seemiller approved these changes
LGTM

2021-09-19 19:12 UTC, joshrosso requested changes

2021-09-20 15:54 UTC, joshrosso approved these changes

2021-09-20 15:54 UTC, merged