[Doc] Troubleshooting bootstrap with tanzu diagnostics
vmware-tanzu/community-edition pull request #1932
Opened 2021-09-23 16:29 UTC by vladimirvivien

This patch documents troubleshooting with the tanzu diagnostics plugin.

Signed-off-by: Vladimir Vivien <vivienv@vmware.com>

## What this PR does / why we need it
This is  doc PR to add documentation for troubleshooting with diagnostics plugin.

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
NONE
```

## Which issue(s) this PR fixes
Fixes: #1715

2021-09-23 16:54 UTC, joshrosso requested changes

2021-09-24 11:46 UTC, kcoriordan submitted a review, later dismissed

2021-09-24 16:50 UTC, joshrosso submitted a review, later dismissed

2021-09-28 16:38 UTC, davidvonthenen approved these changes
looks like feedback by @kcoriordan and @joshrosso has been addressed. going to approve and merge. if there additional feedback, we can follow up with a subsequent PR

2021-09-28 16:43 UTC, merged