Solution Guide Opinionated install package #1559
vmware-tanzu/community-edition pull request #1977
Opened 2021-09-27 16:42 UTC by jorgemoralespou

## What this PR does / why we need it
This guide provides a solution guide that will guide you through creation of packages to provide an opinionated installation experience

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
Solution Guide for single package to provide an opinionated installation experience
```

## Which issue(s) this PR fixes
Fixes: #1559 

## Describe testing done for PR
make mdlint
hugo server on the docs/content folder

## Special notes for your reviewer
This guide builds on top of what's been show in the "Solution guide: Secure ingress on AWS"

Signed-off-by: Jorge Morales Pou jomorales@vmware.com

2021-09-27 17:04 UTC, jpmcb reviewed
Initial thoughts on a shallow read - planning to go in depth and go through the guide on my AWS account

---

Question: does it make sense to update the `Secure ingress` guide to point to this guide as a sort of "next" step? I noticed reading through this that we are referencing that guide as a sort of "first step" in the process. Should they be read one after another? Or are they more separate?

I was a bit confused since I had not previously read the ingress guide so I'm wondering if we could make this more general _or_ explicitly call that guide out as a pre-req

---

Should we have a pre-req section where the users install the carvel tools? We jump into making `ytt` overlays pretty quickly without any links to the homebrew tap or getting those tools

2021-09-28 13:50 UTC, kcoriordan submitted a review, later dismissed

2021-09-29 03:54 UTC, joshrosso requested changes
Awesome guide! Suggestions left throughout. I'm going to try and go through this guide (beyond just reading it) tomorrow.

2021-09-30 14:08 UTC, joshrosso submitted a review, later dismissed
Looks good to me. Let's get @kcoriordan to re-review and comment or approve.

2021-09-30 17:18 UTC, kcoriordan submitted a review, later dismissed

2021-09-30 17:40 UTC, kcoriordan approved these changes

2021-10-04 06:38 UTC, merged