Separate avi vip network
vmware-tanzu/community-edition pull request #2181
Opened 2021-10-06 22:35 UTC by iXinqi

2021-10-08 17:44 UTC, XudongLiuHarold requested changes
Generally, it looks good, needs some minor changes.

2021-10-08 17:44 UTC, XudongLiuHarold commented on addons/packages/ako-operator/1.5.0/README.md
> +| `avi_management_cluster_service_engine_group` | Required | the group name of Service Engine that's to be used by the AKO in management cluster. |
This is good catch, thanks @iXinqi

2021-10-08 17:44 UTC, XudongLiuHarold commented on addons/packages/ako-operator/1.5.0/README.md
> +| `avi_management_cluster_cp_vip_network_name` | Required | describes the name of the management cluster control plane network. |
Can we avoid use `cp`? I think we can use `control_plane`, don't be afraid the name is long, we need it to be clear.

2021-10-08 17:44 UTC, XudongLiuHarold commented on addons/packages/ako-operator/1.5.0/bundle/config/upstream/akooperator/static.yaml
> +            - controlPlaneNetwork
Same here, the field should be optional.

2021-10-08 17:44 UTC, XudongLiuHarold commented on addons/packages/ako-operator/1.5.0/bundle/config/values.yaml
> +    avi_management_cluster_cp_vip_network_name: ""
`cp` is not clear about what it actually meaning, we can change it to `control_plane`

2021-10-12 20:30 UTC, iXinqi commented
Will merge this PR after the network separation feature completed.

2021-10-12 20:30 UTC, closed without merging