Add aviinfrasetting to ako templates
vmware-tanzu/community-edition pull request #2225
Opened 2021-10-12 21:30 UTC by iXinqi

Add AVIInfraSetting to ako templates so that AVIInfraSetting will be created when addon manager deploys ako

2021-10-13 20:37 UTC, HanFa commented on addons/packages/load-balancer-and-ingress-service/1.5.3/bundle/config/upstream/loadbalancerandingressservice/ais.yaml
> +      - networkName: VM Network 2
new line here?

2021-10-13 20:39 UTC, HanFa submitted a review, later dismissed

2021-10-13 20:43 UTC, XudongLiuHarold reviewed
<del>We need to hold this until we get everything done and merge them together.</del>

2021-10-13 20:43 UTC, XudongLiuHarold commented on addons/packages/load-balancer-and-ingress-service/1.5.3/bundle/config/upstream/loadbalancerandingressservice/ais.yaml
> +      - networkName: VM Network 2
new line here

2021-10-27 23:31 UTC, XudongLiuHarold requested changes
Need some changes on ako's template

2021-11-01 23:37 UTC, iXinqi commented on addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/overlays/overlay-ais.yaml
> +      - networkName: #@ values.loadBalancerAndIngressService.config.network_settings.control_plane_network_name
cidr is not required: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/release-1.5.2/docs/upgrade/upgrade.md

2021-11-01 23:37 UTC, iXinqi commented on addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/overlays/overlay-ais.yaml
> +    name: #@ values.loadBalancerAndIngressService.config.controller_settings.control_plane_service_engine_group_name
You're right about this. We change it to the `service_engine_group_name`.

2021-11-01 23:37 UTC, iXinqi commented on addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/upstream/loadbalancerandingressservice/ais.yaml
> +      - networkName: VM Network 2
same above

2021-11-01 23:37 UTC, iXinqi commented on addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/values.yaml
> +      control_plane_service_engine_group_name: MC-SEG
same above

2021-11-02 18:42 UTC, XudongLiuHarold requested changes
Minor changes

2021-11-02 18:42 UTC, XudongLiuHarold commented on addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/upstream/loadbalancerandingressservice/ais.yaml
> +---
This should not be in the base template, because when the user doesn't specify any control plane network, you should not create a AIS.

2021-11-02 18:42 UTC, XudongLiuHarold commented on addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/overlays/overlay-ais.yaml
> +#@overlay/match by=overlay.subset({"kind": "AviInfraSetting"})
You can check if the network name for the control plane is the same as the data network then decide to apply a AIS or not.
You can do something like `ingressclass`here: 
https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/overlays/overlay-statefulset.yaml#L288

https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/load-balancer-and-ingress-service/1.6.1/bundle/config/overlays/overlay-statefulset.yaml#L305

2021-11-05 17:25 UTC, XudongLiuHarold submitted a review, later dismissed
LGTM, thanks!

2021-11-05 22:17 UTC, XudongLiuHarold approved these changes, later dismissed

2021-11-08 18:11 UTC, XudongLiuHarold submitted a review, later dismissed
Good catch @HanFa

2021-11-08 23:33 UTC, XudongLiuHarold approved these changes
LGTM

2021-11-08 23:34 UTC, merged