IPv6 Dual-stack support for Calico Addon
vmware-tanzu/community-edition pull request #2252
Opened 2021-10-13 23:51 UTC by flawedmatrix

## What this PR does / why we need it
This PR leverages existing support in Calico for dualstack configurations and sets the proper Calico configuration and environment variables for ipv4,ipv6 and ipv6,ipv4 dualstack IP families.

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Calico now supports ipv4,ipv6 and ipv6,ipv4 dualstack IP families
```

## Which issue(s) this PR fixes

Part of: https://github.com/vmware-tanzu/tanzu-framework/issues/616

## Describe testing done for PR

We manually modified the calico package to test this new overlay change and deployed it to a docker workload cluster

## Special notes for your reviewer

2021-10-14 04:10 UTC, 12345lcr commented
And please update the [readme](https://github.com/vmware-tanzu/community-edition/blob/94e4185f6c94678b4fac0d8231d286c58724e7f1/addons/packages/calico/3.19.1/README.md) for the ipFamily part

2021-10-20 19:05 UTC, seemiller requested changes
Files look good and tests pass. Just update the docs as requested and we can merge.

2021-10-20 22:38 UTC, seemiller approved these changes

2021-10-21 06:13 UTC, 12345lcr commented
There are a few things that worth to mention:
1. Currently downstream is adding calico 3.19 and setting up automation test pipelines for it. And we are almost done.
2. Previously when I was adding calico 3.19 in upstream tce, there were requirements that I should bring the upstream calico 3.19 packages to downstream pipelines for testing and bring back the result. Due to lack of automation tests back then, some hacky ways and bug fixes were involved and took some time.
3. Once the downstream calico 3.19 is merged, it will be easier to take this pr changes to downstream for testing to make sure these changes won't break anything. And I can take care of that.
4. I can bring the changes to downstream for testing before or after merge and I am ok with both. But I am still not sure about the process that **should the downstream testing results block the upstream pr merge**? @seemiller any comments? Thanks.

2021-10-28 09:47 UTC, 12345lcr approved these changes

2021-10-28 09:49 UTC, merged