Bump kapp controller to version 0.28.0
vmware-tanzu/community-edition pull request #2326
Opened 2021-10-22 21:27 UTC by shivaani0505

## What this PR does / why we need it
Changes for adding kapp controller in tce => release 0.28.0

## Details for the Release Notes 

```release-note
Bump kapp controller to released version 0.28.0
```

## Which issue(s) this PR fixes
Fixes: #2327 

## Describe testing done for PR
ytt --ignore-unknown-comments -f 0.28.0/bundle/config

2021-10-22 23:32 UTC, seemiller requested changes
Remove namespace field in package.yaml

2021-10-25 15:02 UTC, seemiller submitted a review, later dismissed

2021-10-26 16:24 UTC, vijaykatam reviewed
PR description is missing release note section.

2021-10-27 17:11 UTC, cppforlife approved these changes

2021-10-27 19:21 UTC, merged