Standalone overhaul: implements context aware progress animation
vmware-tanzu/community-edition pull request #2401
Opened 2021-10-29 16:50 UTC by jpmcb

All changes related to the standalone-overhaul

---

This PR implements two new methods for the logger:

- `AnimateProgressf` which will animate dots based on the provided format message (and it's args)
- `AnimateStatusf` is similar to `AnimateProgressf` but also takes a string chan that contains the most recent "status". This is intended to be printed via a format string provided as the "message"

In short, this allows us to "animate" both blocking and non blocking calls. For example, this PR also implements animating and on calls to the TkrImageReader download image method.

2021-11-03 19:47 UTC, joshrosso commented on cli/cmd/plugin/standalone-cluster/log/log.go
>  	Progressf(count int, message string, args ...interface{})
Is there a way we can make progressf private or something? Worried about this interface growing too large

2021-11-03 19:53 UTC, joshrosso requested changes
@jpmcb this look really great!

My only feedback is that it feels like our interface declares the need for 3 definitions, where 1 could work. Thoughts? Any way to simply merge Progressf AnimateProgressf and AnimateStatusf?

2021-11-04 22:52 UTC, joshrosso commented
i'm going to merge this, but we'll need to circle back sometime to figure out the `--tty=false` use case. Seems it spreads the status logs out without a line break.

```txt
Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster             Creating cluster
```

When TTY is on, it looks great!

2021-11-04 22:53 UTC, merged

2021-11-08 16:57 UTC, jpmcb commented
https://github.com/vmware-tanzu/community-edition/pull/2473 addresses the problem with `tty=false` logging with the progress animator