feat: 2.3.3 code base;
vmware-tanzu/community-edition pull request #2413
Opened 2021-11-01 11:20 UTC by zyyw

Signed-off-by: Shengwen Yu <yshengwen@vmware.com>

## What this PR does / why we need it

Add Harbor package 2.3.3

## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: #2412  

## Describe testing done for PR

`cd addons/packages/harbor/2.3.3/test`
`make test`

## Special notes for your reviewer

2021-11-01 14:20 UTC, stmcginnis commented
Updated the title and description to include release note. Please make sure to include good descriptions of the change to all issues and PRs. Thanks!

2021-11-01 14:21 UTC, stmcginnis requested changes

2021-11-01 14:21 UTC, stmcginnis commented on addons/packages/harbor/2.3.3/README.md
> +# harbor Package
s/harbor/Harbor/

2021-11-01 14:21 UTC, stmcginnis commented on addons/packages/harbor/2.3.3/README.md
> +This package provides << awesome functionality >> using [harbor](https://INFO_NEEDED).
Please fill in placeholder explaining what the package provides.

2021-11-01 14:21 UTC, stmcginnis commented on addons/packages/harbor/2.3.3/README.md
> +### harbor Configuration
s/harbor/Harbor/

2021-11-01 14:21 UTC, stmcginnis commented on addons/packages/harbor/2.3.3/README.md
> +The follow is a basic guide for getting started with harbor.
Please complete this section or remove.

2021-11-04 19:06 UTC, stmcginnis approved these changes, later dismissed
Updates look good to me, thanks!

2021-11-05 03:39 UTC, heww approved these changes

2021-11-05 04:16 UTC, karuppiah7890 approved these changes
I only checked `test/e2e/addons_config.yaml` from an approval (file ownership) point of view. I'll look at whole PR soon

LGTM!

2021-11-05 04:50 UTC, MinerYang approved these changes
LGTM

2021-11-05 11:08 UTC, heww commented
@seemiller Could you help to review this PR? Seems that the `test/e2e/addons_config.yaml` or `addons/repos/main.yaml` file is modified, so it requires the tce-owners to review this PR. Thanks!

2021-11-05 11:58 UTC, stmcginnis approved these changes
I think with the approval from @MinerYang we should be good to go.

2021-11-05 11:58 UTC, merged