Pinniped Package: remove namespace from JWTauthenticator
vmware-tanzu/community-edition pull request #2482
Opened 2021-11-09 15:06 UTC by benjaminapetersen

Signed-off-by: Benjamin A. Petersen <ben@benjaminapetersen.me>

## What this PR does / why we need it

JWTAuthenticator is a Concierge resource, as of the 0.12.0 package update these are now cluster scoped, there should not be a namespace printed for this resource.

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
NONE
```

## Which issue(s) this PR fixes

Fixes: #

## Describe testing done for PR

## Special notes for your reviewer

2021-11-10 16:34 UTC, ankeesler requested changes
one question, but i think it looks fine as long as you've tested that it works

2021-11-10 16:34 UTC, ankeesler commented on addons/packages/pinniped/0.12.0/bundle/config/upstream/02-pinniped-concierge.yaml
> -namespace: #@ pinniped_concierge_namespace()
don't we still need this? some of the concierge resources are still namespaced (e.g., `Deployment`)

2021-11-10 21:44 UTC, jpmcb commented
Noticed this had WIP in the title - converted to a draft, feel free to mark "Ready for review" when it's good to go!

2021-11-23 18:45 UTC, benjaminapetersen commented
Closing this now, will come back to it in a bit.

2022-01-19 15:35 UTC, closed without merging