Adding "Tanzu Community Edition Takes Off!" Blog
vmware-tanzu/community-edition pull request #2526
Opened 2021-11-11 21:31 UTC by pnbrown

## What this PR does / why we need it
Adds a new blog to the site

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
NONE
```

## Describe testing done for PR

Rendered the site locally in Hugo

## Special notes for your reviewer

2021-11-11 21:44 UTC, stmcginnis commented on docs/site/content/posts/02-vmware-tanzu-community-edition-takes-off.md
> +native landscape and the value of being able to easily consume them with Tanzu Community Edition.
This line should have some leading spaces to align with the first line of the bullet item.

2021-11-11 21:44 UTC, stmcginnis commented on docs/site/content/posts/02-vmware-tanzu-community-edition-takes-off.md
> + Shipley's suggestions](https://tanzu.vmware.com/developer/blog/expanding-the-developer-toolbox-with-vmware-tanzu-community-edition/) for a few open source tools that you'll want to use with Tanzu Co
Here too. Need to remove extra spaces after the opening `-`, then align this with the start of the text there.

2021-11-11 22:13 UTC, pnbrown commented
I removed all the spaces at the beginning so that there's just one.

2021-11-11 22:16 UTC, stmcginnis commented on docs/site/content/posts/02-vmware-tanzu-community-edition-takes-off.md
> +native landscape and the value of being able to easily consume them with Tanzu Community Edition.
Still needs leading spaces on continued line.

2021-11-11 22:16 UTC, stmcginnis commented on docs/site/content/posts/02-vmware-tanzu-community-edition-takes-off.md
> + Shipley's suggestions](https://tanzu.vmware.com/developer/blog/expanding-the-developer-toolbox-with-vmware-tanzu-community-edition/) for a few open source tools that you'll want to use with Tanzu Co
One more space needed to line up.

2021-11-11 22:23 UTC, pnbrown commented
Or @stmcginnis should there be the same number of spaces in front of all of them greater than one?

2021-11-11 22:53 UTC, stmcginnis commented on docs/site/content/posts/02-vmware-tanzu-community-edition-takes-off.md
> +native landscape and the value of being able to easily consume them with Tanzu Community Edition.
Yeah, the `n` in native should line up with the `A` from Always.

2021-11-11 22:53 UTC, stmcginnis commented on docs/site/content/posts/02-vmware-tanzu-community-edition-takes-off.md
> + Shipley's suggestions](https://tanzu.vmware.com/developer/blog/expanding-the-developer-toolbox-with-vmware-tanzu-community-edition/) for a few open source tools that you'll want to use with Tanzu Co
Same here with the `S` and `E`.

2021-11-15 14:47 UTC, jonasrosland requested changes
Minor nitpick in the last link, otherwise this looks great!

2021-11-15 14:47 UTC, jonasrosland commented on docs/site/content/posts/02-vmware-tanzu-community-edition-takes-off.md
> +us](http://www.tanzucommunityedition.io) today!
Make sure to link to https://tanzucommunityedition.io, instead of http, and www.

2021-11-15 15:20 UTC, jonasrosland approved these changes

2021-11-15 15:40 UTC, jpmcb approved these changes
LGTM!! Is this ready to go? 👀

2021-11-15 15:41 UTC, pnbrown commented
I think so if the things @stmcginnis pointed out are alright.

2021-11-15 16:29 UTC, stmcginnis commented
We can clean those up later. mdlint isn't complaining, and since they are bullets instead of numbers it's kind of hidden/irrelevant that the formatting is off.

2021-11-15 16:30 UTC, merged