packages/contour: Expose loadBalancerIP in config
vmware-tanzu/community-edition pull request #2661
Opened 2021-12-03 22:32 UTC by doddatpivotal

If applied, this commit will all a user to specify desired load balancer IP address for Contour's Envoy service.

Fixes #2622

Signed-off-by: Dodd Pfeffer <dpfeffer@vmware.com>

## Describe testing done for PR
I'm not quite sure how to test this.

## Special notes for your reviewer
I attempted to find all relavent docs that would need to be updated as well.
I felt making the update to the latest patch release of the last two minors was sufficient.  I'm open to feedback.

2021-12-04 00:01 UTC, skriss requested changes
Thanks for the PR @doddatpivotal! Looks pretty good, really just one substantive comment.

> I felt making the update to the latest patch release of the last two minors was sufficient. I'm open to feedback.

Yep that makes sense to me too, we should drop some of the older versions soon anyway.

The last thing we'll need to do is push the updated packages to the registry, and update the `package.yaml` files to have the right SHAs. @seemiller is there a suggested process here for when the contributor is not a package owner / does not have access to the registry? Probably just makes sense for me to do a follow-up PR after this merges to push the packages and update the SHAs?

2021-12-06 16:08 UTC, sunjayBhatia reviewed
cant think of anything besides @skriss' review 👍🏽

2021-12-06 16:33 UTC, doddatpivotal commented on addons/packages/contour/1.18.2/bundle/config/overlays/update-envoy-service.yaml
> +  #@ if data.values.envoy.service.type == "LoadBalancer":
Great feedback.  I've updated in a second commit.

2021-12-06 16:34 UTC, doddatpivotal commented on addons/packages/contour/1.18.2/package.yaml
> +                  default: Local
Great feedback.  I've updated in a second commit.

2021-12-06 16:36 UTC, doddatpivotal commented
@skriss I believe I have addressed the substantive feedback.  Please let me know if there is more I can do.

2021-12-06 16:38 UTC, skriss commented on addons/packages/contour/1.18.2/bundle/config/overlays/update-envoy-service.yaml
> +  #@ if data.values.envoy.service.type == "LoadBalancer":
Note the second line in the suggestion too - `#@overlay/match missing_ok=True`, needs to be added since this field is not in the upstream manifest.

2021-12-06 16:45 UTC, skriss commented
FYI my basic approach to validating this is to manually edit the `values.yaml` to include the different permutations of envoy service type + load balancer IP, and then to run `ytt -f addons/packages/contour/1.19.1/bundle/config | grep loadBalancerIP` and inspect the output.

2021-12-06 17:03 UTC, doddatpivotal commented
@skriss thank you for the unit test suggestion.  That helped to quickly identify the flaw in my previous commit and have confidence that the new one works.

2021-12-06 17:12 UTC, skriss approved these changes
LGTM, thanks @doddatpivotal! I'll plan to follow up with a PR that pushes the packages to the registry and bumps the package.yaml SHAs.

2021-12-09 16:44 UTC, dvonthenen approved these changes
deferring review to others in thread here

2021-12-09 16:44 UTC, merged