Create OpenAPIV3 schema for vsphere-csi package and generate package with the schema
vmware-tanzu/community-edition pull request #2832
Opened 2022-01-12 21:54 UTC by blc1996

Signed-off-by: Lucheng Bao <luchengb@vmware.com>

## What this PR does / why we need it

Create OpenAPIV3 schema for vsphere-csi package and generate package with the schema

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Create OpenAPIV3 schema for vsphere-csi package and generate package with the schema
```

## Which issue(s) this PR fixes

Fixes: #2831 

## Describe testing done for PR

Tested with ytt commands and ran make generate-openapischema-package locally

## Special notes for your reviewer

YTT version needs to be bumped to latest (0.38.0)

2022-03-04 16:40 UTC, dvonthenen commented
@vijaykatam I think we are looking for a review on this

2022-03-04 20:57 UTC, vijaykatam approved these changes, later dismissed

2022-03-23 22:10 UTC, seemiller commented
@vijaykatam @blc1996 Sorry about this, be we got a merge conflict. Could you please resolve?

2022-04-06 20:09 UTC, seemiller commented
@vijaykatam @blc1996 ping - can someone merge these 2 files?

2022-04-06 20:14 UTC, blc1996 commented
Hi @seemiller , I'm not sure if we still want to merge this. Let me sync up with @peterochodo as he is not taking care of CSI package.

2022-04-06 20:16 UTC, blc1996 commented
> Hi @seemiller , I'm not sure if we still want to merge this. Let me sync up with @peterochodo as he is not taking care of CSI package.

Looks like Peter is creating another PV CSI package. I'll resolve the conflict and get it merged.

2022-04-06 21:19 UTC, blc1996 commented
Hi @vijaykatam, could you take a look at this PR again? Thanks!

2022-05-20 06:39 UTC, stmcginnis commented
Looks like this has a merge conflict again. Is this still needed?

2022-05-20 15:06 UTC, seemiller requested changes

2022-05-20 15:06 UTC, seemiller commented on addons/packages/vsphere-csi/2.3.0/package.yaml
> +          image: projects.registry.vmware.com/tce/vsphere-csi@sha256:069990d21488f6ffea7fe5cc33e074297294a52f3f202fbe346745e8fbc55aef
```suggestion
          image: projects.registry.vmware.com/tce/vsphere-csi@sha256:337a51c8d72de40e1815eb56d98cb6ee0912f2fa7ac391f4f9711d910ece7506
```

2022-05-20 15:06 UTC, seemiller commented on addons/packages/vsphere-csi/2.4.1/package.yaml
> +          image: projects.registry.vmware.com/tce/vsphere-csi@sha256:ffb6731278dc157d75ff56e8a4e8f6b5f8f08cc108a86e42c0cb8204ae7203ef
```suggestion
          image: projects.registry.vmware.com/tce/vsphere-csi@sha256:ed2b01baf6e93a5a7bfb7d79f3602735ab4cd3ab0e3a68c9856a64e6894a3ae3
```
Locally I rebased with main and pushed the package, this is the SHA that I got.

2022-05-20 15:08 UTC, seemiller commented
If this PR is still needed, I would recommend rebasing with the main branch, pushing the packages and verifying the SHAs in the package.yaml files.

2022-06-13 14:16 UTC, stmcginnis commented
Can this be closed?

2022-06-13 15:36 UTC, blc1996 commented
Closing this MR. If this is needed, please open it against main branch once more @vijaykatam . Thanks!

2022-06-13 15:36 UTC, closed without merging