Change tty control flag to `--tty-disable`
vmware-tanzu/community-edition pull request #2850
Opened 2022-01-13 21:44 UTC by stmcginnis

Bool flags for cobra commands are defaulted to true when present, and
the syntax of needing an = to set the value to something other than that
isn't the most intuitive.

Rather than have our tty control flag default to true, requiring the
user to explicitly set the value to switch it to false, this simplifies
things by changing the flag to `--tty-disable`. That makes its usage a
little simpler in that when it is actually used, the intent of using it
is to disable the TTY formatting in our output. So now it can just be
used as a simple flag.

2022-01-13 23:08 UTC, joshrosso requested changes
@stmcginnis I'm finding `--tty false` to no longer error out, but also not long be respected.

![image](https://user-images.githubusercontent.com/6200057/149423125-7477ecbb-6c48-4be3-9394-671e16a635cf.png)

Thoughts?

2022-01-13 23:13 UTC, stmcginnis commented
> Thoughts?

Yep. With the way you provided this as `--tty false` and no cluster name, cobra is interpreting this as "set tty to true" and "cluster name is 'false'. It's a syntax problem with how cobra handles that switch. Unless you specify `--tty=false`, it will not work the way you are expecting.

I left a comment on Slack, but wonder since the use of this flag will usually be to disable tty, maybe we should invert things and rename it to `--no-tty`.

2022-01-13 23:23 UTC, joshrosso commented
> 

Ooops, yeah that makes sense. Didn't realize I left out the cluster name (arg)!

However, i'm a little surprised, so cobra **cannot** evaluate `--tty false`? It needs to be `tty=false`?

2022-01-14 14:51 UTC, stmcginnis commented
>However, i'm a little surprised, so cobra cannot evaluate --tty false? It needs to be tty=false?

That is my understanding. Maybe @jpmcb can confirm, but I had to walk through in a debugger to confirm that `--tty false` was setting the tty variable to `true` and `false` was one of the `args` being passed through to the cmd.

2022-01-14 15:27 UTC, joshrosso commented
Perhaps it would be more clear and best practice to introduce an argumentless flag. 

For example: `--tty=false` to `--tty-disable`.

Let's get @jpmcb input as to whether this is a good practice. To me, `--tty-disable` seems more clear.

2022-01-14 15:28 UTC, joshrosso requested changes
preventing merge while we has these UX details out.

2022-01-14 15:53 UTC, jpmcb commented
Sean is correct; this is a symptom of how `spf13/pflag` is implemented which is what Cobra uses for persistent flags.

`spf13/pflag` is doing a best effort here with what it's given as a "default" value:

- If it finds `--tty`, it's going to treat this as a switch flag and set this to true (which is already the default value). Note here that it won't attempt to interpret any next "word" as an argument to this flag since it's condition has already been satisfied as a boolean flag. 
- If it finds _no `--tty` flag, it's going to use the default value we've set which is `true`.
- If it finds `-tty={value}` it's going to attempt to use that value as the new flag bool.

Again, in the case where it is seeing just `--tty`, it's going to interpret that as just a boolean switch, take the argument after and use that as the argument to the create command.

There's actually a good little chunk about what's happening here and the possibility to change the default behavior given no flag is set the pflag library: https://github.com/spf13/pflag#setting-no-option-default-values-for-flags

I agree with Josh, I think the best thing to do here is set a `--tty-disable` flag that acts as an inverse switch to what we were doing and turns TTY off.

2022-01-14 16:17 UTC, joshrosso commented
Thanks for the details @jpmcb.

@stmcginnis can we move forward with, `--tty-disable`. I prefer it over `--no-tty` because i'd like the noun `tty` to come before the verb `disable`.

2022-01-14 17:05 UTC, stmcginnis commented
Updated, but now I see there are merge conflicts. Rebase on its way.

2022-01-14 17:26 UTC, joshrosso commented
thanks! I'll review and test this shortly.

2022-01-14 17:47 UTC, joshrosso commented
### `--tty-disable` is now available :heavy_check_mark: 

```
josh@u:~$ ./tanzu-unmanaged-cluster-linux_amd64 create --help

Create an unmanaged Tanzu cluster. This sets up a Kubernetes cluster and installs
Tanzu packages. Once the environment is bootstrapped, your kubectl context is
automatically switched, enabling you to begin using the kubectl and tanzu CLIs.

No configuration is required for this command. However, you can setup a config
file by running tanzu unmanaged-cluster configure <cluster name>. This config file can
then be referenced using the -f flag.

When create is called, it respects the following precedence for all configuration:

1. flags (most respected)
2. environment variables
3. config file
4. defaults (least respected)

Usage:
  tanzu unmanaged-cluster create <cluster name> [flags]

Flags:
  -c, --cni string            The CNI to deploy; default is antrea
  -f, --config string         A config file describing how to create the Tanzu environment
  -h, --help                  help for create
      --pod-cidr string       The CIDR for Pod IP allocation; default is 10.244.0.0/16
  -p, --port-map strings      Ports to map between container node and the host (format: '80:80/tcp' or just '80')
      --provider string       The infrastructure provider for cluster creation; default is kind
      --service-cidr string   The CIDR for Service IP allocation; default is 10.96.0.0/16
      --skip-preflight        Skip the preflight checks; default is false
  -t, --tkr string            The URL to the image containing a Tanzu Kubernetes release
      --tty-disable           Disable log stylization and emojis

Global Flags:
      --log-file string   Log file path
  -v, --verbose int32     Number for the log level verbosity(0-9)
```

### default create uses stylization :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/6200057/149559622-895cf430-285e-4507-8b7c-ee084a1139e1.png)

### `--tty-disable` removes stylization :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/6200057/149559753-8c91a20c-db23-4c50-8b88-af00811c15c2.png)

### TTY autodetect still works (validated in cmd prompt, windows) :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/6200057/149561328-5dc8b045-d00d-4149-b81f-470bf402e258.png)

2022-01-14 17:47 UTC, joshrosso approved these changes

2022-01-14 17:47 UTC, merged