Add  to auto-generated Table of Contents #2641
vmware-tanzu/community-edition pull request #2868
Opened 2022-01-18 21:34 UTC by seemiller

## What this PR does / why we need it

The auto-generated table of contents for the package documentation subfolder needed to be updated for a new package creation guide.

## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: #2641

## Describe testing done for PR

## Special notes for your reviewer

2022-01-18 21:35 UTC, kcoriordan submitted a review, later dismissed

2022-01-18 22:13 UTC, joshrosso requested changes
blocking for lint errors.

2022-01-25 12:37 UTC, kcoriordan approved these changes

2022-02-01 20:24 UTC, joshrosso approved these changes

2022-02-01 20:25 UTC, merged