Update release and test scripts to include `unmanaged-cluster` plugin
vmware-tanzu/community-edition pull request #2869
Opened 2022-01-19 11:25 UTC by karuppiah7890

## What this PR does / why we need it

Updates release and test scripts to include `unmanaged-cluster` plugin

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
NONE
```

## Which issue(s) this PR fixes

Fixes: #2867 

## Describe testing done for PR

Yet to do testing

## Special notes for your reviewer

None

2022-01-20 18:16 UTC, joshrosso requested changes
Noticing on this and `main` that `make package-release` fails with:

```
+ popd
~/d/community-edition
+ for env in ${ENVS}
+ binaryname=windows_amd64
+ extension=
+ [[ windows_amd64 = *windows* ]]
+ extension=.exe
+ scriptextension=.sh
+ [[ windows_amd64 = *windows* ]]
+ scriptextension=.bat
+ PACKAGE_DIR=hack/release/../../build/tce-windows-amd64-v0.10.0-fake.4
+ rm -rf hack/release/../../build/tce-windows-amd64-v0.10.0-fake.4
+ mkdir -p hack/release/../../build/tce-windows-amd64-v0.10.0-fake.4/bin
+ cp -f /tmp/tce-release/tanzu-framework/artifacts/core/v0.10.0/tanzu-core-windows_amd64.exe hack/release/../../build/tce-windows-amd64-v0.10.0-fake.4/bin/tanzu.exe
cp: cannot stat '/tmp/tce-release/tanzu-framework/artifacts/core/v0.10.0/tanzu-core-windows_amd64.exe': No such file or directory
make: *** [Makefile:240: package-release] Error 1
```

Let me know if there's any need to resolve this it in this PR.

2022-01-27 16:51 UTC, dvonthenen commented
I did a `make release` on your branch @karuppiah7890 and it looks like it works for me. @joshrosso can you try a full rebuild using `make release`?

2022-01-28 21:17 UTC, joshrosso commented
yup, works great for me.

sorry about that, must have been my environment!

2022-01-28 21:17 UTC, joshrosso approved these changes

2022-01-28 21:18 UTC, merged