Adds GitHub action stale bot
vmware-tanzu/community-edition pull request #2877
Opened 2022-01-19 18:12 UTC by jpmcb

## What this PR does / why we need it
Adds `stale` label to PRs and issues after 30 days
and closes them after 15 days.

Avoids the stale label for PRs with milestones attached.

Ref GitHub stale action: https://github.com/actions/stale

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Added github actions stale bot to label / close stale issues and PRs
```

## Which issue(s) this PR fixes
Fixes: #2876

## Describe testing done for PR
N/a

## Special notes for your reviewer
n/a

2022-01-19 18:18 UTC, jpmcb commented
Up to feedback on messaging and length of time we plan to close issues and/or PRs 👀

2022-01-19 18:35 UTC, joshrosso requested changes
Is there a way to set this up such that it only applies to issues with:

* no milestone
* icebox milestone

I want to insulate us against long-running issues that are placed in things like future releases e.g. `v0.12.0` or the `upcoming` milestone.

2022-01-19 19:23 UTC, jpmcb commented
There is the ability to provide a `exempt-milestone` with a list of milestones that the stale action should ignore. Not great since we'd have to keep a list in the config of the milestones we have and are using. I don't think there's an elegant way to do a `! icebox milestone` type of logic so I opened:

- [ ] https://github.com/actions/stale/issues/657

2022-01-20 15:29 UTC, jpmcb commented
Per a discussion with Josh, updated this to label issues/PRs `stale` after 60 days and close after another 30 days; 90 in total. This also ignores the `upcoming` milestone for long running issues and PRs.

2022-01-20 15:46 UTC, joshrosso approved these changes

2022-01-20 15:47 UTC, merged