unmanaged-cluster: support no CNI and failed CNI
vmware-tanzu/community-edition pull request #2941
Opened 2022-01-26 02:07 UTC by joshrosso

## What this PR does / why we need it

This commit adds support for creating clusters without install CNI. It
also enables cluster creation to complete successfully when a CNI
package fails to resolve.

For creating clusters without CNI, a user may set the CNI configuration
value to "none". For example, cluster creation can occur as follows:

tanzu uc create testme --cni=none

Users will receive a warning message that no CNI was installed, and the
installation will complete.

For when a CNI is specified but is invalid, for example:

tanzu uc create testme --cni=beepboopnotreal

Users will receive a warning message that no CNI package was found, but
the install will still complete. This is because the cluster is still
successfully started and the user could choose to remedy or troubleshoot
after bootstrapping.

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
unmanaged-clusters support none for CNI value, preventing an install of CNI after cluster creation.
```

## Which issue(s) this PR fixes

Fixes: https://github.com/vmware-tanzu/community-edition/issues/2939
Fixes: https://github.com/vmware-tanzu/community-edition/issues/2940

## Describe testing done for PR

### CNI does not install when set to `none` :heavy_check_mark:.

![image](https://user-images.githubusercontent.com/6200057/151091358-70b17ebc-368c-4aaa-96e2-a87c82d4e780.png)

### CNI skipped when cannot resolve package (rather than fail) :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/6200057/151091406-ea2e9ee1-07d8-460b-9a96-dd48cbc6dda4.png)

### CNI Selection still works as expected :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/6200057/151091450-0b3660ed-c324-466f-a76a-db457bfdec3a.png)

## Special notes for your reviewer

None

2022-01-26 18:54 UTC, jpmcb requested changes
I'm guessing you didn't mean to commit either of these files?

-  `cli/cmd/plugin/unmanaged-cluster/test.png`
-  `docs/site/.hugo_build.lock`

2022-01-26 19:18 UTC, jpmcb commented
### Default behavior still works ✅ 
![image](https://user-images.githubusercontent.com/23109390/151229595-c7ac40f0-fcbd-4617-b9b0-dabd9c7177e9.png)

### Selecting `none` CNI works ✅ 
![image](https://user-images.githubusercontent.com/23109390/151230033-cd336b19-fc3d-4496-927e-667d33e87191.png)
```
❯ k get pods -A
NAMESPACE            NAME                                                 READY   STATUS    RESTARTS   AGE
kube-system          coredns-558bd4d5db-4r8bj                             0/1     Pending   0          116s
kube-system          coredns-558bd4d5db-fp9jd                             0/1     Pending   0          116s
kube-system          etcd-test-cluster-control-plane                      1/1     Running   0          118s
kube-system          kube-apiserver-test-cluster-control-plane            1/1     Running   0          118s
kube-system          kube-controller-manager-test-cluster-control-plane   1/1     Running   0          118s
kube-system          kube-proxy-6m6pf                                     1/1     Running   0          116s
kube-system          kube-scheduler-test-cluster-control-plane            1/1     Running   0          118s
local-path-storage   local-path-provisioner-547f784dff-xg4x8              0/1     Pending   0          116s
tkg-system           kapp-controller-f7dbbcb4f-hp5jl                      1/1     Running   0          113s

```

### Non-resolving CNI works ✅ 
![image](https://user-images.githubusercontent.com/23109390/151230874-b71eb633-8438-4cff-b953-39e25eddd768.png)

### Setting a valid CNI works ✅ 
![image](https://user-images.githubusercontent.com/23109390/151231311-b75c4137-738a-4615-b906-5a469385867c.png)

This is amazing!!!

2022-01-27 15:47 UTC, joshrosso commented
> I'm guessing you didn't mean to commit either of these files?
> 
> * `cli/cmd/plugin/unmanaged-cluster/test.png`
> * `docs/site/.hugo_build.lock`
> * `cli/cmd/plugin/unmanaged-cluster/--help`
> 
> Otherwise, code in `tanzu.go` looking good!

I did not, removed those files :+1:.

Ready for approve/merge.

2022-01-27 19:25 UTC, jpmcb approved these changes

2022-01-27 19:26 UTC, merged