Package docs should warn about comments in custom values.yaml file #2909
vmware-tanzu/community-edition pull request #3107
Opened 2022-02-10 16:35 UTC by seemiller

## What this PR does / why we need it

Minor update to package docs to instruct removing comments from custom values.yaml files.

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Minor update to package docs to instruct removing comments from custom values.yaml files.
```

## Which issue(s) this PR fixes
Fixes: #2909

## Describe testing done for PR

## Special notes for your reviewer

2022-02-10 17:54 UTC, joshrosso requested changes
We should likely move away from recommending this approach altogether and have folks lookup the schema to form their own values file.

Can we update this to provide that guidance instead? Or is there a technical limitation making looking up the package source still compelling?

2022-03-04 16:46 UTC, seemiller commented
@joshrosso I'm good with re-working docs to reference the schema approach. However, only 6 of the current 26 packages are using schemas. So would you consider approving this issue on the basis of it supporting existing packages without schemas and we create a new issue to update docs instructing the use of schemas going forward? Or I'm happy to use this issue if you prefer.

2022-03-04 19:23 UTC, joshrosso commented
gotcha, yes

2022-03-04 19:23 UTC, joshrosso approved these changes

2022-03-04 19:24 UTC, merged