Implements saving `kind` config during cluster creation for `unmanaged-cluster` creation
vmware-tanzu/community-edition pull request #3299
Opened 2022-03-01 22:29 UTC by jpmcb

## What this PR does / why we need it
Now saves the kind config used during bootstrapping for unmanaged-clusters

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
unmanaged-cluster saves kind configuration used during bootstrapping
```

## Which issue(s) this PR fixes
Fixes: https://github.com/vmware-tanzu/community-edition/issues/3061

## Describe testing done for PR
Created a new cluster:

```
$ tanzu unmanaged-cluster create my-cluster --worker-node-count 2
```

And see cluster is created and the config file is found:
```
$ pwd
/home/jmcb/.config/tanzu/tkg/unmanaged/my-cluster

$ cat kindconfig.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster
nodes:
    - role: control-plane
      image: projects.registry.vmware.com/tce/kind/node:v1.21.5
    - role: worker
      image: projects.registry.vmware.com/tce/kind/node:v1.21.5
    - role: worker
      image: projects.registry.vmware.com/tce/kind/node:v1.21.5
networking:
    ipFamily: ipv4
    apiServerAddress: 127.0.0.1
    podSubnet: 10.244.0.0/16
    serviceSubnet: 10.96.0.0/16
    disableDefaultCNI: true
    kubeProxyMode: iptables
```

2022-03-03 16:50 UTC, jorgemoralespou commented
This is great. This will help with customizing ProviderConfiguration.

2022-03-04 16:38 UTC, dvonthenen approved these changes, later dismissed

2022-03-04 19:05 UTC, joshrosso commented on cli/cmd/plugin/unmanaged-cluster/cluster/kind.go
> +	configDir := ".config/tanzu/tkg/unmanaged"
don't we have these conventions defined somewhere? I feel like we need to these paths as well for things like the log file?

2022-03-04 19:06 UTC, joshrosso commented on cli/cmd/plugin/unmanaged-cluster/cluster/kind.go
> +	configDir := ".config/tanzu/tkg/unmanaged"
if not, let's make sure they go into a package somewhere that can easily reference this common destination (e.g. `unmanagedConfigHome`)

2022-03-04 19:17 UTC, joshrosso requested changes
Works great on my machine. Love this feature.

@jpmcb can we resolve https://github.com/vmware-tanzu/community-edition/pull/3299/files#r819833782.

We care about this location is many places, so i'd really like a consistent way to retrieve it.

If you feel strong it belongs in another PR/commit, that's cool -- just would like to see us fast follow merging this with that.

_i'm also happy just doing the work here_

Let us know :rocket:

2022-03-09 16:17 UTC, jpmcb commented
@joshrosso - this should be ready to go now!

I ended up doing _a bit_ of a refactor of how the config dirs get loaded. We were doing it in a few different places, so I thought it'd make sense to land it in the `config` package since that's where we base all other configs.

Let me know if this is out of scope of this PR and I can roll it back

2022-03-09 18:56 UTC, joshrosso approved these changes
looks great; works great :fire:

2022-03-09 18:56 UTC, merged