Bump Harbor package to 2.4.2
vmware-tanzu/community-edition pull request #3648
Opened 2022-03-22 08:13 UTC by zyyw

Signed-off-by: Shengwen Yu <yshengwen@vmware.com>

## What this PR does / why we need it

Bump Harbor package to 2.4.2

## Which issue(s) this PR fixes

Fixes: #2731 

## Describe testing done for PR

1. ut
`cd addons/packages/harbor/2.4.0/test`
`make test`
2. functional test for tracing which was introduced in Harbor 2.4.2

## Special notes for your reviewer

2022-03-28 07:59 UTC, MinerYang commented
lgtm

2022-03-29 01:31 UTC, MinerYang approved these changes, later dismissed

2022-03-29 07:56 UTC, jorgemoralespou commented
Have these issues been addressed along with the version bump?
- https://github.com/vmware-tanzu/community-edition/issues/3591
- https://github.com/vmware-tanzu/community-edition/issues/3491
- https://github.com/vmware-tanzu/community-edition/issues/2942
- https://github.com/vmware-tanzu/community-edition/issues/1994

2022-03-29 20:05 UTC, seemiller reviewed
Along with Jorge, I too am curious if this release addresses any outstanding Harbor package issues.

2022-03-30 02:56 UTC, zyyw commented
Hi @jorgemoralespou / @seemiller , 
These issues are addressed:
* https://github.com/vmware-tanzu/community-edition/issues/3491 is updated in the issue (nothing to be address from the codebase perspective)
* https://github.com/vmware-tanzu/community-edition/issues/2942  is addressed in this 2.4.2 version
* https://github.com/vmware-tanzu/community-edition/issues/1994 is addressed in this PR https://github.com/vmware-tanzu/community-edition/pull/2563, also included in 2.4.2 version

This one is not:
* https://github.com/vmware-tanzu/community-edition/issues/3591

Please let me know if you have further concerns.

2022-03-30 17:52 UTC, seemiller requested changes

2022-03-30 17:52 UTC, seemiller commented on addons/packages/harbor/2.4.2/test/e2e/harbor_suite_test.go
> +	version := findPackageAvailableVersion(packageName, "2.3.3")
```suggestion
	version := findPackageAvailableVersion(packageName, "2.4.2")
```

I assume that this should be `2.4.2` for the `2.4.2` version of the package?

2022-03-31 01:38 UTC, MinerYang submitted a review, later dismissed
lgtm

2022-03-31 03:30 UTC, heww commented
Hi @zyyw I think https://github.com/vmware-tanzu/community-edition/issues/3591 must be fixed in this PR, it's a P0 issue.

2022-03-31 14:25 UTC, seemiller approved these changes

2022-03-31 14:28 UTC, merged