Add vsphere-cpi 1.22.6 1.21.3 1.20.1
vmware-tanzu/community-edition pull request #3757
Opened 2022-03-28 18:19 UTC by lubronzhan

## What this PR does / why we need it

This PR bumps CPI 1.22.6, 1.21.3, 1.20.1, which have the fix for IP disappeared for node after node is restarted

## Which issue(s) this PR fixes

Fixes: #

## Describe testing done for PR

## Special notes for your reviewer

2022-03-29 20:44 UTC, HanFa approved these changes, later dismissed
LGTM

2022-03-30 14:55 UTC, seemiller requested changes
I left 3 suggestions to update the image SHA in the package.yaml files. Are you using imgpkg to push the packages to Harbor? If so, I would recommend updating to a newer version. All of the new bundles that were pushed for this PR only have 1 tag. If that tag is ever removed, Harbor will garbage collect and delete that image. Newer versions of imgpkg will add the SHA as a tag to prevent this.

2022-03-30 17:21 UTC, HanFa commented on addons/packages/vsphere-cpi/1.20.1/package.yaml
> +          image: projects.registry.vmware.com/tce/vsphere-cpi@sha256:3764207049a4b0b7d8e18073e6a105ff5edea87e397292c2a893ece756055103
the SHA I got is `be17e733f2ef2a48184d6fd6aed21876ffd0f9149c15455ec3368cfc4227d2c2`

2022-03-30 17:21 UTC, HanFa commented on addons/packages/vsphere-cpi/1.22.6/package.yaml
> +          image: projects.registry.vmware.com/tce/vsphere-cpi@sha256:a132e8b4eef8c5df5c816b9a8fa41a2e418f1de7fde5b22b32e1d9896ed74d01
SHA I got is the same `3201da54c4a87672949f038697da883575f86755fcc32137409ae85c38d720d7`

2022-03-30 17:22 UTC, HanFa commented on addons/packages/vsphere-cpi/1.21.3/package.yaml
> +          image: projects.registry.vmware.com/tce/vsphere-cpi@sha256:8b9442c8f2159fbd833da7dcc1a0f6a727340e23c4b5ca82d8287a96a5c8ffa5
SHA is the same `76738506b9d31ed56dca180a8e9585932a8fd96d8e6d97ffdaae61a9a3ea8fc1`

2022-03-30 18:56 UTC, seemiller approved these changes

2022-03-30 18:56 UTC, merged