community page content updates
vmware-tanzu/community-edition pull request #3915
Opened 2022-04-05 21:42 UTC by michow

Signed-off-by: michow <michow@smalltalk.agency>

## What this PR does / why we need it

## Which issue(s) this PR fixes

Fixes: #

## Describe testing done for PR

## Special notes for your reviewer

2022-04-11 16:11 UTC, dvonthenen commented
This looks ok to me, but want to get @kcoriordan feedback on it

2022-04-11 16:12 UTC, dvonthenen approved these changes, later dismissed

2022-04-12 18:50 UTC, stmcginnis submitted a review, later dismissed
Looks good to me.

2022-04-12 19:53 UTC, microwavables commented
Sorry - need to change the link for agenda / notes for monthly community meetings after a meeting I had today...

2022-04-12 19:55 UTC, microwavables requested changes

2022-04-12 19:55 UTC, microwavables commented on docs/site/content/community/_index.html
> +                    <li><a href="https://hackmd.io/CiuO4V0AT6WL_TgA47MXBA">Meeting Agenda and Notes</a></li>
```suggestion
                    <li><a href="https://hackmd.io/EA962cUBRwODRluxTtW_Yw">Meeting Agenda and Notes</a></li>
```

2022-04-13 10:15 UTC, kcoriordan submitted a review, later dismissed

2022-04-15 16:28 UTC, stmcginnis approved these changes

2022-04-15 16:28 UTC, merged