Add kpack-dependencies package
vmware-tanzu/community-edition pull request #3941
Opened 2022-04-07 16:05 UTC by tylerphelan

- Initial release version 0.0.5
- Bundle is distributed from projects.registry.vmware.com/kpack/dependencies

## What this PR does / why we need it

Adding the kpack dependencies package to TCE

## Which issue(s) this PR fixes

Fixes: https://github.com/vmware-tanzu/community-edition/issues/3668

## Describe testing done for PR

Integration testing with kpack package.
Test coverage includes builders and image creation functionality.

## Special notes for your reviewer

There are 3 important things users must know so we tried to make them clear in the docs:
1. The kpack package is a hard dependency and it must be installed first.
2. To install kpack-dependencies package the user only needs to provide the `kp_default_repository`, however it MUST be the same value used to install the kpack package.
  - This is because the authentication credentials used to install kpack are the same credentials used to write to `kp_default_repository` in the kpack-dependencies package.
3. The resources that are created by the kpack dependencies package cannot be modified.
  - This is because when deployed by kapp controller, resources lifecycle is managed entirely by kapp controller and any user changes would be overwritten.
  - This is in contrast to other kpack workflows that recommend managing and modifying existing ClusterStore, ClusterStack, and ClusterBuilder resources.
  - It should be made clear that if users want custom solutions they will need to create and manage them manually.

The buildpacks and stacks for each release will be available at the package-for-kpack-dependencies github release page: https://github.com/vmware-tanzu/package-for-kpack-dependencies/releases/tag/v0.0.5

At the time of this PR the https://github.com/vmware-tanzu/package-for-kpack-dependencies page is not yet approved for being converted to a public repo but is in progress.

2022-04-08 17:30 UTC, kartiklunkad26 commented
@seemiller for review!

2022-04-11 22:40 UTC, seemiller requested changes

2022-04-11 22:40 UTC, seemiller commented on addons/packages/kpack-dependencies/0.0.5/README.md
> +* [Creating an image using kubectl](#creating-an-image-using-kube 6ctl)
@tylerphelan I think there is a typo here - `kube 6ctl`,  and the link is not rendering correctly.
```
[Creating an image using kubectl](#creating-an-image-using-kube 6ctl)
```

2022-04-12 19:45 UTC, seemiller submitted a review, later dismissed

2022-04-12 19:45 UTC, seemiller commented
@tylerphelan @kartiklunkad26 this PR is pulling in 0.0.5, but I see that 0.0.9 is available, would you want to bump the PR to use the latest version of the package? (Latest version also has the readme fixes I asked for)

2022-04-13 14:30 UTC, tylerphelan commented
updated to 0.0.9 latest kpack dependencies release

2022-04-13 15:39 UTC, seemiller commented
Created a package repo for testing - `projects-stg.registry.vmware.com/tce/main@sha256:9da3352a8702e5f6ecf8160d26dc5beb59430501e980677ac521b43c932653ac`

2022-04-13 15:51 UTC, kcoriordan commented on addons/packages/kpack-dependencies/0.0.9/README.md
> +After installing kpack dependencies dependencies do not need to be manually installed, and you can immediately create source-to-image builds.
```suggestion
After installing kpack, dependencies do not need to be manually installed, and you can immediately create source-to-image builds.
```

2022-04-13 15:51 UTC, kcoriordan commented on addons/packages/kpack-dependencies/0.0.9/README.md
> +   in step #5.
should this be step 4?

2022-04-13 16:02 UTC, kcoriordan commented on addons/packages/kpack-dependencies/0.0.9/README.md
> +   the `spec.git.revision` on the Image Resource configured in step #6.
Should this refer to step 3 --- Create a kpack Image Resource.

2022-04-13 16:05 UTC, kcoriordan commented on addons/packages/kpack-dependencies/0.0.9/README.md
> +   You can tail the logs for the Image Resource with the kp cli used in step #6.
should this be step 2?

2022-04-13 16:13 UTC, tylerphelan commented
@kcoriordan resolved by removing all references to other steps as they are unnecessary

2022-04-13 16:16 UTC, kcoriordan approved these changes, later dismissed

2022-04-13 16:31 UTC, tylerphelan commented
@seemiller @kcoriordan 
added some context for troubleshooting the installation in the README due to:

>The installation does not "fail fast" and will reconcile until the timeout if the installation is in a failing state.

2022-04-13 16:33 UTC, kcoriordan approved these changes

2022-04-13 23:08 UTC, seemiller approved these changes

2022-04-13 23:08 UTC, merged