Switch App-Toolkit example to use kpack ClusterBuilder
vmware-tanzu/community-edition pull request #3956
Opened 2022-04-08 19:13 UTC by ryanmattcollins

## What this PR does / why we need it
- Changes App-Toolkit example to rely on kpack's default service account in the kpack namespace
- Corrects the usage of workload-user-sa by App-Toolkit (which was not being used)
- Changes the example kpack Builder to ClusterBuilder to be namespace agnostic
- Removes some unnecessary artifacts that were lingering in the App-Toolkit's test directory

## Describe testing done for PR
Ran through App-Toolkit test suite

2022-04-11 19:53 UTC, kartiklunkad26 approved these changes, later dismissed
Looks good to me!

2022-04-12 20:28 UTC, seemiller requested changes

2022-04-12 20:28 UTC, seemiller commented on addons/packages/app-toolkit/0.1.0/README.md
> +1. Use `ytt` to insert the values from the above `supplychain-example-values.yaml` into the Kuberentes resource definitions below. You can inspect the files and see which resources each one is creati
```suggestion
1. Use `ytt` to insert the values from the above `supplychain-example-values.yaml` into the Kubernetes resource definitions below. You can inspect the files and see which resources each one is creating
```

2022-04-14 21:18 UTC, seemiller approved these changes

2022-04-14 21:19 UTC, merged