Makes unmanaged cluster create objects idempotent
vmware-tanzu/community-edition pull request #4039
Opened 2022-04-14 18:51 UTC by jpmcb

- Makes kapp controller deployment, packagerepos, and packageinstalls
  idempotent. If the object exists on the cluster, won't attempt to
  create it, returns found objects.
- Noop cluster return an error to inform users that delete does not
  clean up cluster from provider

## Which issue(s) this PR fixes

Fixes: #3580

## Describe testing done for PR
First, create a new kind cluster to use as an "existing" cluster:
```
$ kind create cluster --name test
```

Run tanzu `create` with existing cluster:
```
$ tanzu unmanaged-cluster create --cni=none -e ~/.kube/config
```

Delete files known by unmanaged-cluster for this:
```
$ tanzu unmanaged-cluster delete kind-test

🧪 Deleting cluster: kind-test
   Warning - could not delete cluster through provider. Be sure to manually delete cluster. Error: cluster not deleted. Existing and noop clusters require manual deletion
   Local config files directory deleted: /home/jmcb/.config/tanzu/tkg/unmanaged/kind-test
Failed delete operation. Error: cluster not deleted. Existing and noop clusters require manual deletion
```

And re-attaching works 👍🏼 
```
$ tanzu unmanaged-cluster create --cni=none -e ~/.kube/config
```

## Special notes for your reviewer
Not sure if this is the best approach or if there's a better way to go about this. Hoping to get some feedback from @joshrosso & @stmcginnis on this approach

2022-04-14 18:52 UTC, jpmcb commented
cc @jorgemoralespou since you had made the original request for this 👀

2022-04-15 00:58 UTC, joshrosso requested changes
I'm not so sure on this one.

I get the intent, however I think we need to give deeper thought to what it means to "attach" to an existing cluster and what the longer-term lifecycle management of workloads (such as kapp-controller) should look like.

For example, today, if I have a cluster where I deployed a `kapp-controller`, perhaps from a TKG package through cluster essentials, and UC is pointed at it (perhaps on accident), it will error out:

```
📧 Installing kapp-controller
failed to install kapp-controller, Error: namespaces "tkg-system" already exists
Error: exit status 9
```

I think this **is** the correct behavior.

I'm not saying no to an approach like this long-term, but I think we need better definitions around "attaching" to a cluster and what the expectations are.

2022-04-15 15:07 UTC, jpmcb commented
> I think we need to give deeper thought to what it means to "attach" to an existing cluster and what the longer-term lifecycle management of workloads (such as kapp-controller) should look like.

> I'm not saying no to an approach like this long-term, but I think we need better definitions around "attaching" to a cluster and what the expectations are.

Agreed - this first stab gives us a good idea of what that behavior might look like, but _it is_ a drifting UX since now with this change, if the objects are there, we skip installing instead of erroring out.

> I think we should revisit this topic in v0.13.0

Sounds good - I'll move #3580 into that project

2022-04-15 15:56 UTC, jorgemoralespou commented
>  today, if I have a cluster where I deployed a kapp-controller, perhaps from a TKG package through cluster essentials, and UC is pointed at it (perhaps on accident), it will error out:
   ```
   📧 Installing kapp-controller
   failed to install kapp-controller, Error: namespaces "tkg-system" already exists
   Error: exit status 9
   ```
>I think this is the correct behavior.

I agree. The caveat here is that I would expect some way of "identifying" who did what, so that, if `uc cluster create` was the   way, then it takes the actions to be idempotent, else, can error out saying, `hey, you already have this, installed by some other means, it's up to you to fix that`.

What I was asking was for the `tanzufy a cluster` action to be idempotent, meaning that, if I tanzufy a cluster I already tanzufied before, to not get an error. But yes, if it wasn't me the one that did it, I would agree that an error/confirmation can be the way.

2022-04-15 16:31 UTC, jpmcb commented
> I would expect some way of "identifying" who did what, so that, if uc cluster create was the way, then it takes the actions to be idempotent, else, can error out saying, hey, you already have this, installed by some other means, it's up to you to fix that.

Isn't that out of scope of what `unmanaged-cluster` is doing? We don't want to manage objects on the cluster in the way that managed clusters do. In my opinion, at this time, `unmanaged-cluster` should _not_ be attempting to lifecycle clusters or their components.

> What I was asking was for the tanzufy a cluster action to be idempotent, meaning that, if I tanzufy a cluster I already tanzufied before, to not get an error.

This PR was the only way I saw to accomplish that; when objects by name exist on a cluster, we skip creating them. That unfortunately, as Josh said, has some drifting ux and we need to better define what attaching and managing those objects means.

2022-04-15 16:44 UTC, jorgemoralespou commented
> Isn't that out of scope of what unmanaged-cluster is doing? We don't want to manage objects on the cluster in the way that managed clusters do. In my opinion, at this time, unmanaged-cluster should not be attempting to lifecycle clusters or their components.

I think you've misunderstood my comment. And probably this is the result of having in UC a side effect being a feature, which is "tanzufy a cluster". My point being that, if this function tanzufies a cluster, needs to be idempotent, and for that, it should know whether the "tanzu" related resources were added via this way, so that `idempotency` can be expected. This is just a matter of adding some annotations to the generated resources to understand provenance.

In any case, I agree that better definition of experience might be needed.

2022-04-18 14:24 UTC, joshrosso commented
> Sounds good - should we move https://github.com/vmware-tanzu/community-edition/issues/3580 into that project?

Done.

> In any case, I agree that better definition of experience might be needed.

:100:

2022-10-31 20:09 UTC, closed without merging