Cleaned up unused code
vmware-tanzu/community-edition pull request #4401
Opened 2022-05-06 11:03 UTC by jorgemoralespou

## What this PR does / why we need it
Removes all unused code in the extension

## Which issue(s) this PR fixes
Fixes: #4385

## Describe testing done for PR
Create, delete cluster, and all variations.

This PR needs to merge code from https://github.com/vmware-tanzu/community-edition/pull/4380 and other related Docker Extension PR and do validations again.

Signed-off-by: Jorge Morales Pou <jorgemoralespou@gmail.com>

2022-05-06 15:14 UTC, jpmcb requested changes
🛑  - marking this as something we'll want to merge after the `v0.12.0` release Tuesday to prevent too much code churn

2022-05-06 16:13 UTC, jorgemoralespou commented
@jpmcb @joshrosso @stmcginnis Merged conflicts resolved, after I rebased on merged PR. This should be ready for after release.

2022-05-31 17:45 UTC, dvonthenen approved these changes, later dismissed
LGTM

2022-06-01 19:34 UTC, stmcginnis submitted a review, later dismissed

2022-06-06 22:09 UTC, jpmcb approved these changes

2022-06-06 22:18 UTC, merged