Update App Toolkit 0.2.0 Documentation to be more consistent
vmware-tanzu/community-edition pull request #4781
Opened 2022-06-14 15:14 UTC by ryankilroy

## What this PR does / why we need it
Updates the docs for App Toolkit to follow TAP convention

2022-06-21 18:58 UTC, seemiller requested changes

2022-06-21 18:58 UTC, seemiller commented on addons/packages/app-toolkit/0.2.0/README.md
> +Install `secretgen-controller` based on the version in the secretgen-controller package docs. For example, if the version is 0.8.0:
```suggestion
Install `secretgen-controller` based on the version in the secretgen-controller package docs. For example, if the version is 0.7.1:
```
the `0.8.0` version of secretgen-controller is not in the package repository.

2022-06-21 18:58 UTC, seemiller commented on addons/packages/app-toolkit/0.2.0/README.md
> +tanzu secret registry add registry-credentials --server REGISTRY_URL --username REGISTRY_USER --password REGISTRY_PASS --export-to-all-namespaces`
```suggestion
tanzu secret registry add registry-credentials --server REGISTRY_URL --username REGISTRY_USER --password REGISTRY_PASS --export-to-all-namespaces
```
extraneous closing `

2022-06-21 20:02 UTC, ryankilroy commented
Good catches, thanks @seemiller !

2022-06-29 15:07 UTC, seemiller approved these changes

2022-06-29 15:13 UTC, merged