Updated to knative serving 1.5.0
vmware-tanzu/community-edition pull request #4802
Opened 2022-06-15 20:51 UTC by nader-ziada

## What this PR does / why we need it

- add package for knative serving 1.5.0, 
this is a small release with mostly fixes so I don't think there is any need for configuration changes 

## Which issue(s) this PR fixes

Fixes: #4746 

## Describe testing done for PR

2022-06-15 20:52 UTC, nader-ziada commented
/cc @xtreme-sameer-vohra

2022-06-17 21:12 UTC, xtreme-sameer-vohra commented
cc @vmware-tanzu/knative-owners

2022-06-21 16:08 UTC, seemiller requested changes

2022-06-21 16:08 UTC, seemiller commented on addons/packages/knative-serving/1.5.0/package.yaml
> +            image: projects.registry.vmware.com/tce/knative-serving@sha256:648b8eb811806513e9681912899be3bdd086b8b7d99d0b7d52dbf44024ee858f
```suggestion
            image: projects.registry.vmware.com/tce/knative-serving@sha256:01dd43ed368cb42985204916aacd64c9ef0b159b3b7436d4de8076d1134bf4b6
```
@nader-ziada I pushed the package to our OCI registry. Please accept this suggestion with the new image URL and I can get this merged!

2022-06-21 18:59 UTC, seemiller approved these changes

2022-06-21 19:00 UTC, merged