Add Contour 1.20.2
vmware-tanzu/community-edition pull request #4804
Opened 2022-06-15 22:08 UTC by sunjayBhatia

## What this PR does / why we need it
Add package for newly release Contour 1.20.2

See release notes: https://github.com/projectcontour/contour/releases/tag/v1.20.2

Also adds ipv6 compatibility via setting listen addresses to ipv6 for Contour/Envoy since Contour/Envoy are set up to
listen on ipv6 with ipv4 compatibility, see: https://github.com/projectcontour/contour/pull/4584

## Which issue(s) this PR fixes
Fixes: #4324 
(actually makes obsolete, since we don't need a package flag)

## Describe testing done for PR
locally in cluster and package unit tests

## Special notes for your reviewer
N/A

2022-06-15 22:09 UTC, sunjayBhatia commented
Still TODO: Haven't pushed the package bundle yet, but would like to get validation on the content first (esp. the ipv6 compatibility part)

2022-06-15 22:10 UTC, sunjayBhatia commented
Alternative to https://github.com/vmware-tanzu/community-edition/pull/4594, can be used as an alternate approach

2022-06-15 22:17 UTC, sunjayBhatia commented
This maybe needs some thought/consideration, I haven’t been able to break it/tell anything is wrong really, stats listeners/health listeners all work as well as the envoy http/s listeners 👀

2022-06-21 17:45 UTC, seemiller requested changes
Please delete the readme from the docs folder.

I've pushed the package to projects-stg.registry.vmware.com and created a package repository for testing:
```
projects-stg.registry.vmware.com/tce/main@sha256:6290251b0bf919e94b18c4d94ecebed975e82a943caa52f1be4090c7129710a4
```

2022-06-21 18:37 UTC, skriss requested changes
One little nit, otherwise looks good to me, would be good to get @youngnick's thoughts on the ipv6 stuff too though.

2022-06-21 22:21 UTC, sunjayBhatia commented on addons/packages/contour/1.20.2/package.yaml
> +            image: projects.registry.vmware.com/tce/contour@sha256:0128c3458d57cd637c198b3a6377bb1eca6e23301f27710ac29d9d0ee1c5bd09
updated

2022-06-24 14:03 UTC, skriss submitted a review, later dismissed

2022-06-24 17:56 UTC, skriss approved these changes
LGTM, I guess the one downside to the latest refactor is that if we add any new cmd-line args upstream, we'll have to remember to add them here too since we're now replacing them all, but that shouldn't be too common.

2022-06-24 20:30 UTC, skriss commented
I think it's fine since we really shouldn't be adding more CLI flags, just something to try to remember on the off chance we do.

2022-06-27 15:23 UTC, sunjayBhatia commented
@seemiller this is ready for another review when you get a chance

2022-06-28 14:56 UTC, seemiller approved these changes

2022-06-28 14:56 UTC, merged