add metrics-server v0.6.1
vmware-tanzu/community-edition pull request #4872
Opened 2022-06-22 23:13 UTC by ggpaue

## What this PR does / why we need it

## Which issue(s) this PR fixes

Fixes: #

## Describe testing done for PR

## Special notes for your reviewer

2022-06-24 21:32 UTC, seemiller requested changes
I think the `test.yaml` file is extraneous, and it is causing an error with the overlays.
```
cd addons/packages/metrics-server/0.6.1/bundle/config
ytt -f .
```
yields the error:
```
ytt: Error: Overlaying (in following order: overlays/overlay-apiservice.yaml, overlays/overlay-deployment.yaml, overlays/overlay-namespace.yaml, overlays/update-strategy-overlay.yaml):
  Document on line overlays/overlay-apiservice.yaml:5:
    Expected number of matched nodes to be 1, but was 2 (lines: test.yaml:184, upstream/components.yaml:181)
```

2022-06-24 22:04 UTC, ggpaue commented on addons/packages/metrics-server/0.6.1/package.yaml
> +          image: projects.registry.vmware.com/tce/metrics-server@sha256:4fa580c9b185d44f39847cd2347c8110b3a38d775e674ce77bc3b2569067f4c0
@seemiller should this image be manually pushed?

2022-06-24 22:04 UTC, ggpaue commented
> I think the `test.yaml` file is extraneous, and it is causing an error with the overlays.
> 
> ```
> cd addons/packages/metrics-server/0.6.1/bundle/config
> ytt -f .
> ```
> 
> yields the error:
> 
> ```
> ytt: Error: Overlaying (in following order: overlays/overlay-apiservice.yaml, overlays/overlay-deployment.yaml, overlays/overlay-namespace.yaml, overlays/update-strategy-overlay.yaml):
>   Document on line overlays/overlay-apiservice.yaml:5:
>     Expected number of matched nodes to be 1, but was 2 (lines: test.yaml:184, upstream/components.yaml:181)
> ```

ah I added by mistake, now deleted it

2022-06-27 22:02 UTC, seemiller requested changes

2022-06-27 22:42 UTC, ggpaue commented on addons/packages/metrics-server/0.6.1/package.yaml
> +          image: projects.registry.vmware.com/tce/metrics-server@sha256:4fa580c9b185d44f39847cd2347c8110b3a38d775e674ce77bc3b2569067f4c0
thank you very much! @seemiller, I have pushed the changed SHA

2022-06-28 14:51 UTC, seemiller approved these changes

2022-06-28 14:51 UTC, merged