fix Enlightning typo
vmware-tanzu/community-edition pull request #4928
Opened 2022-06-29 23:06 UTC by michow

## What this PR does / why we need it
fix typo on Resources page

## Which issue(s) this PR fixes

Fixes: #

## Describe testing done for PR

## Special notes for your reviewer

2022-06-30 01:01 UTC, stmcginnis requested changes

2022-06-30 01:01 UTC, stmcginnis commented on docs/site/themes/template/layouts/_default/resources.html
> +                                <h3>Enlightning</h3>
The current spelling is actually correct.

https://www.merriam-webster.com/dictionary/enlightening

2022-06-30 21:23 UTC, michow commented
@jpmcb @stmcginnis @jkotzen I do not have the permissions to reopen this pull request, someone from your side will have to do it. The name of the YouTube series referred to on the Resources page is indeed spelled "Enlightning" without the additional "e".

2022-06-30 22:17 UTC, stmcginnis commented
Please update the title and description to actually reflect what is being done and why. Thanks!

2022-07-01 18:42 UTC, michow commented
@stmcginnis @jpmcb title and description have been updated

2022-07-01 18:43 UTC, stmcginnis approved these changes
Thanks!

2022-07-01 18:44 UTC, merged