Skip sudo on install of running as root
vmware-tanzu/community-edition pull request #4960
Opened 2022-07-03 12:08 UTC by stmcginnis

## What this PR does / why we need it

Our install script attempts to figure out the best place to install the
`tanzu` binary to. It will look in the user's home directory for a
`~/bin` path, and if that is not found it will try to install to the
common path of `/usr/local/bin`.

In the latter case, in normal cases this needs to be run using sudo to
have permissions to install to the system-wide path. But when running as
root, the use of sudo is a noop since there are no elevated permissions
needed.

On most systems, when running as root the `sudo` command is still
present somewhere in `$PATH`. But some systems do not have this
available. So despite the fact that the root user doesn't actually need
`sudo`, the command fails due to the command not being found.

To avoid this situation, this changes the install script to detect if we
are running as root, and if so, run the install to the system-wide path
without trying to invoke using sudo.

## Which issue(s) this PR fixes

Fixes: #4957

2022-07-03 15:50 UTC, dvonthenen approved these changes

2022-07-03 15:50 UTC, dvonthenen requested changes
I think there is actually a modification that needs to be done for the uninstall script too if we want to be consistent

2022-07-05 15:29 UTC, jpmcb approved these changes
This looks good to me!

2022-07-13 18:54 UTC, dvonthenen approved these changes

2022-07-13 18:54 UTC, merged