Update CODEOWNERS #4982
vmware-tanzu/community-edition pull request #4983
Opened 2022-07-07 03:49 UTC by seemiller

## What this PR does / why we need it

Adds owners for the following packages:
- azuredisk-csi-driver
- kubeapps

## Which issue(s) this PR fixes

Fixes: #4982

## Describe testing done for PR

## Special notes for your reviewer

2022-07-07 15:14 UTC, jpmcb requested changes
I've given write access to both teams but there's a misspelling in the name of the kubeapps team. Then this should be good!

2022-07-07 15:14 UTC, jpmcb commented on CODEOWNERS
> +addons/packages/kubeapps @vmware-tanzu/pkg-kubapps-owners
Misspelled:

```diff
- addons/packages/kubeapps @vmware-tanzu/pkg-kubapps-owners
+ addons/packages/kubeapps @vmware-tanzu/pkg-kubeapps-owners
```

2022-07-07 18:02 UTC, seemiller commented on CODEOWNERS
> +addons/packages/kubeapps @vmware-tanzu/pkg-kubapps-owners
Fixed!

2022-07-08 17:11 UTC, jpmcb approved these changes

2022-07-08 17:11 UTC, merged